### ISSUE TITLE
Rename repo to "bootcamp" or similar

### ISSUE THREAD

**Issue by nicktimko** [amarallab/Introduction-to-Python-Programming-and-Data-Science#2]
Repo name is obnoxiously long: it's easy enough to rename, and GH will [redirect the old name to the new name](https://github.com/blog/1508-repository-redirects-are-here) _excepting the GH pages site_ (https://amarallab.github.io/Introduction-to-Python-Programming-and-Data-Science). Between now and the next bootcamp it'd be nice to tamp it down to something simpler. (also then the GH pages site becomes https://amarallab.github.io/bootcamp or whatever)

**Comment by adamrpah** [comment]
Bootcamp is the style of teaching, not what the repository content is. Ideally in the future we will be able to offer multiple bootcamps on different topics or at different levels, so I don't want to give this a generic label.

I am fine with renaming it but I will want it to be a part of a branding for the course. If as a group we want a different name and can agree upon one then that will be fine.

**Comment by nicktimko** [comment]
The "Bootcamp" done by "Amaral Lab" has been basically the same Python/Data science one, three times over. I don't like the idea of attempting to either future-proof a name or make it "fully descriptive". The point is that it's distinctive, unique, and easy to type: "project-narblar", for instance. I'd prefer that over a 7-word, hyphenated, mixed case title that gives rise to URLs that barely fit on a single line.

I named Joao's Forecite thing and some other site that gets 8 million visits a month, for what it's worth. ;)

**Comment by adamrpah** [comment]
This is a lot closer to an interactive textbook than a website.

The 'future' isn't that far off (we're charging ahead, hopefully other courses soon).

Like I said, as 'Amaral Lab', if we find a different name that fits as good branding let's go for it.

Parts/projects that are code (i.e. the things that you work on) can and should be named like github projects. I see them as core functions of teaching a bootcamp (i.e. not specific to this material) and could benefit from following that convention.

This repository is not a codebase, it is actual content. Others have also used a naming scheme similar to textbooks when releasing content (see Cam Davidson-Pilon or Chris Fonnesbeck).
